# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_home:
    pattern:  /
    defaults: { _controller: NimbleBoardBundle:Index:index }

_productBacklog:
  pattern: /product_backlog
  defaults: { _controller: NimbleBoardBundle:Story:listStories }

_storyAdd:
  pattern: /story/add
  defaults: { _controller: NimbleBoardBundle:Story:addOrEdit }

_storyEdit:
  pattern: /story/edit/{id}
  defaults: { _controller: NimbleBoardBundle:Story:addOrEdit }

_storyDelete:
  pattern: /story/delete/{id}
  defaults: { _controller: NimbleBoardBundle:Story:delete, confirm: false }

_storyDeleteConfirm:
  pattern: /story/delete/{id}/confirm
  defaults: { _controller: NimbleBoardBundle:Story:delete, confirm: true }

_storySetCoordinates:
  pattern: /story/setCoordinates
  defaults: { _controller: NimbleBoardBundle:Story:setCoordinates }