# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_home:
    pattern:  /
    defaults: { _controller: NimbleBoardBundle:Project:list }

_productBacklog:
  pattern: /project/{projectId}/backlog
  defaults: { _controller: NimbleBoardBundle:Story:listStories }

_storyAdd:
  pattern: /project/{projectId}/story/add
  defaults: { _controller: NimbleBoardBundle:Story:addOrEdit }

_storyEdit:
  pattern: /story/edit/{id}
  defaults: { _controller: NimbleBoardBundle:Story:addOrEdit }

_storyDelete:
  pattern: /story/delete/{id}
  defaults: { _controller: NimbleBoardBundle:Story:delete, confirm: false }

_storyDeleteConfirm:
  pattern: /story/delete/{id}/confirm
  defaults: { _controller: NimbleBoardBundle:Story:delete, confirm: true }

_storySetCoordinates:
  pattern: /story/setcoordinates
  defaults: { _controller: NimbleBoardBundle:Story:setCoordinates }

_storySetStatus:
  pattern: /story/setstatus
  defaults: { _controller: NimbleBoardBundle:Story:setStatus }

_projectList:
  pattern: /projects
  defaults: { _controller: NimbleBoardBundle:Project:list }

_projectAdd:
  pattern: /project/add
  defaults: { _controller: NimbleBoardBundle:Project:addOrEdit }

_projectEdit:
  pattern: /project/edit/{id}
  defaults: { _controller: NimbleBoardBundle:Project:addOrEdit }

_projectDelete:
  pattern: /project/delete/{id}
  defaults: { _controller: NimbleBoardBundle:Project:delete, confirm: false }

_projectDeleteConfirm:
  pattern: /project/delete/{id}/confirm
  defaults: { _controller: NimbleBoardBundle:Project:delete, confirm: true }

_sprintAdd:
  pattern: /project/{projectId}/sprint/add
  defaults: { _controller: NimbleBoardBundle:Sprint:addOrEdit }

_sprintList:
  pattern: /project/{projectId}/sprints
  defaults: { _controller: NimbleBoardBundle:Sprint:list }

_sprintBacklog:
  pattern: /sprint/{id}/backlog
  defaults: { _controller: NimbleBoardBundle:Sprint:backlog }

_sprintEdit:
  pattern: /sprint/edit/{id}
  defaults: { _controller: NimbleBoardBundle:Sprint:addOrEdit }

_sprintDelete:
  pattern: /sprint/delete/{id}
  defaults: { _controller: NimbleBoardBundle:Sprint:delete, confirm: false}

_sprintDeleteConfirm:
  pattern: /sprint/delete/{id}/confirm
  defaults: { _controller: NimbleBoardBundle:Sprint:delete, confirm: true }

_sprintAddStories:
  pattern: /sprint/{id}/addstories
  defaults: { _controller: NimbleBoardBundle:Sprint:addStories }

_sprintAddStory:
  pattern: /sprint/addStory
  defaults: { _controller: NimbleBoardBundle:Sprint:addStory }