<?php

namespace Agile\NimbleBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends EntityRepository
{
  public function findOneByIdJoinedToStoriesAndProject($id)
  {
    $query = $this->getEntityManager()->createQuery('
      select sp, s from NimbleBoardBundle:Sprint sp
      left join sp.stories s
      join sp.project p
      where sp.id = :id
    ')->setParameter('id', $id);
    try {
      return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
      return null;
    }
  }
}
