<?php

namespace Agile\NimbleBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryRepository extends EntityRepository
{
  public function findOneByIdJoinedToProject($id)
  {
    $query = $this->getEntityManager()->createQuery('
      select s, p from NimbleBoardBundle:Story s
      join s.project p
      where s.id = :id
    ')->setParameter(':id', $id);
    try {
      return $query->getSingleResult();
    } catch(\Doctrine\ORM\NoResultException $e) {
      return null;
    }
  }

  /**
   * User for product backlog : all stories in project which are not in a sprint
   */
  public function findByProjectWithoutSprint($projectId)
  {
    $query = $this->getEntityManager()->createQuery('
      select s, p from NimbleBoardBundle:Story s
      join s.project p
      where p.id = :projectId and s.sprint is null
    ')->setParameter(':projectId', $projectId);
    return $query->getResult();
  }
}
